### ISSUE TITLE
Under os x environment compiler error

### ISSUE THREAD

**Issue by RoyinRolland** [flexVDI/launcher-mobile#1]
Building the following recipes: gettext spice-protocol libffi zlib glib libpng pixman expat bzip2 freetype fontconfig gtk-doc-lite openssl nopoll gstreamer-1.0 libxml2 libogg cairo harfbuzz pango libvorbis libtheora libvisual orc tremor gst-plugins-base-1.0 libjpeg-turbo opus spice-gtk spiceglue
[(1/30) gettext -> already built ]
[(2/30) spice-protocol -> already built ]
[(3/30) libffi -> already built ]
[(4/30) zlib -> already built ]
[(5/30) glib -> already built ]
[(6/30) libpng -> already built ]
[(7/30) pixman -> already built ]
[(8/30) expat -> already built ]
[(9/30) bzip2 -> already built ]
[(10/30) freetype -> already built ]
[(11/30) fontconfig -> already built ]
[(12/30) gtk-doc-lite -> already built ]
[(13/30) openssl -> fetch ]
-----> Step done
[(13/30) openssl -> extract ]
-----> Step done
[(13/30) openssl -> configure ]
-----> Step done
[(13/30) openssl -> compile ]
-----> Step done
[(13/30) openssl -> install ]
making all in crypto...
making all in crypto/objects...
make[2]: Nothing to be done for `all'.
making all in crypto/md4...
make[2]: Nothing to be done for`all'.
making all in crypto/md5...
make[2]: Nothing to be done for `all'.
making all in crypto/sha...
make[2]: Nothing to be done for`all'.
making all in crypto/mdc2...
make[2]: Nothing to be done for `all'.
making all in crypto/hmac...
make[2]: Nothing to be done for`all'.
making all in crypto/ripemd...
make[2]: Nothing to be done for `all'.
making all in crypto/whrlpool...
make[2]: Nothing to be done for`all'.
making all in crypto/des...
make[2]: Nothing to be done for `all'.
making all in crypto/aes...
make[2]: Nothing to be done for`all'.
making all in crypto/rc2...
make[2]: Nothing to be done for `all'.
making all in crypto/rc4...
make[2]: Nothing to be done for`all'.
making all in crypto/idea...
make[2]: Nothing to be done for `all'.
making all in crypto/bf...
make[2]: Nothing to be done for`all'.
making all in crypto/cast...
make[2]: Nothing to be done for `all'.
making all in crypto/camellia...
make[2]: Nothing to be done for`all'.
making all in crypto/seed...
"error.log" 736L, 93165C
ld: warning: URGENT: building for OSX, but linking in object file (libcrypto.a(cms_enc.o)) built for iOS. Note: This will be an error in the future.
ld: warning: URGENT: building for OSX, but linking in object file (libcrypto.a(cms_ess.o)) built for iOS. Note: This will be an error in the future.
ld: warning: URGENT: building for OSX, but linking in object file (libcrypto.a(cms_pwri.o)) built for iOS. Note: This will be an error in the future.
ld: warning: URGENT: building for OSX, but linking in object file (libcrypto.a(cms_kari.o)) built for iOS. Note: This will be an error in the future.
ld: warning: URGENT: building for OSX, but linking in object file (libcrypto.a(pqueue.o)) built for iOS. Note: This will be an error in the future.
ld: warning: URGENT: building for OSX, but linking in object file (libcrypto.a(ts_err.o)) built for iOS. Note: This will be an error in the future.
ld: warning: URGENT: building for OSX, but linking in object file (libcrypto.a(ts_req_utils.o)) built for iOS. Note: This will be an error in the future.
ld: warning: URGENT: building for OSX, but linking in object file (libcrypto.a(ts_req_print.o)) built for iOS. Note: This will be an error in the future.
ld: warning: URGENT: building for OSX, but linking in object file (libcrypto.a(ts_rsp_utils.o)) built for iOS. Note: This will be an error in the future.
ld: warning: URGENT: building for OSX, but linking in object file (libcrypto.a(ts_rsp_print.o)) built for iOS. Note: This will be an error in the future.
ld: warning: URGENT: building for OSX, but linking in object file (libcrypto.a(ts_rsp_sign.o)) built for iOS. Note: This will be an error in the future.
ld: warning: URGENT: building for OSX, but linking in object file (libcrypto.a(ts_rsp_verify.o)) built for iOS. Note: This will be an error in the future.
ld: warning: URGENT: building for OSX, but linking in object file (libcrypto.a(ts_verify_ctx.o)) built for iOS. Note: This will be an error in the future.
ld: warning: URGENT: building for OSX, but linking in object file (libcrypto.a(ts_lib.o)) built for iOS. Note: This will be an error in the future.
ld: warning: URGENT: building for OSX, but linking in object file (libcrypto.a(ts_conf.o)) built for iOS. Note: This will be an error in the future.
ld: warning: URGENT: building for OSX, but linking in object file (libcrypto.a(ts_asn1.o)) built for iOS. Note: This will be an error in the future.
ld: warning: URGENT: building for OSX, but linking in object file (libcrypto.a(srp_lib.o)) built for iOS. Note: This will be an error in the future.
ld: warning: URGENT: building for OSX, but linking in object file (libcrypto.a(srp_vfy.o)) built for iOS. Note: This will be an error in the future.
ld: warning: URGENT: building for OSX, but linking in object file (libcrypto.a(cmac.o)) built for iOS. Note: This will be an error in the future.
ld: warning: URGENT: building for OSX, but linking in object file (libcrypto.a(cm_ameth.o)) built for iOS. Note: This will be an error in the future.
ld: warning: URGENT: building for OSX, but linking in object file (libcrypto.a(cm_pmeth.o)) built for iOS. Note: This will be an error in the future.
ld: can't write output file: libcrypto.1.0.0.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: **\* [link_a.darwin] Error 1
make[3]: **\* [do_darwin-shared] Error 2
make[2]: **\* [libcrypto.1.0.0.dylib] Error 2
make[1]: **\* [shared] Error 2
make: **\* [build_crypto] Error 1
Running command 'make install'

Recipe 'openssl' failed at the build step 'install'
Select an action to proceed:
[0] Enter the shell
[1] Rebuild the recipe from scratch
[2] Rebuild starting from the failed step
[3] Skip recipe
[4] Abort

**Comment by kevinscience** [comment]
I have same problem. Is there anyway to solve?

**Comment by slp** [comment]
I've just fixed the OpenSSL recipe. Pull the changes from cerbero, and try again.
