### ISSUE TITLE
Lacking some files

### ISSUE THREAD

**Issue by yll2wcf** [flexVDI/launcher-mobile#4]
Hi, i'm currently working on an iOS project which using your library. I met some problem during the compiling by following the steps in your document. Could you please send me the following files to fix it?
libnopoll.a

libspice-client-glib-2.0.a

libspiceglue.a
Thank you so much and waiting for your response.

**Comment by slp** [comment]
Hi,

You need to build those libraries using our cerbero fork. Please refer to the project's README.md for more info: https://github.com/flexVDI/launcher-mobile/blob/master/README.md
